export const gameInfoActionTypes = {
  TRIGGER_ANIMATION: "TRIGGER_ANIMATION",
  END_TURN: "END_TURN",
  LOSE_CHECKER: "LOSE_CHECKER",
  MOVE_CHECKER: "MOVE_CHECKER",
  SELECT_CHECKER: "SELECT_CHECKER",
  START_GAME: "START_GAME",
  UNSELECT_CHECKER: "UNSELECT_CHECKER",
  GAME_FINISHED: "GAME_FINISHED",
}
